### ISSUE TITLE
Bump `rustler_precompiled` in order to work correctly with the `HEX_CACERTS_PATH` env var.

### ISSUE THREAD

**Issue by DnOberon** [elixir-explorer/explorer#1013]
Behind corporate firewalls we often need to set CA certificates in order to get erlang's http methods to work correctly. Up until a while ago, `rustler_precompiled` did not respect that env var. They have since fixed the problem and we'd ask that you bump up to the latest version so we can get this package to work behind corporate firewalls.

Thanks from the team at Idaho National Laboratory!

**Comment by philss** [comment]
Hey @DnOberon, in theory we don't need to bump `rustler_precompiled` because the version definition is flexible, so you can use versions from `v0.7` until before the `v1.0`.

So you may need to update the `rustler_precompiled` version of your projects. To do that, you can either:

* force the build to avoid cache usage when using [`Mix.install/2`](https://hexdocs.pm/mix/Mix.html#install/2-options):
  * `Mix.install([{:explorer, "~> 0.10"}], force: true)`
* update the dependency of a mix project with `mix deps.update rustler_precompiled`

Please let me know if this works for you.

**Comment by DnOberon** [comment]
I’ll pass this on to the team and let you know!

**Comment by DnOberon** [comment]
Apparently, I misunderstood the issue. When we push `wasmex` to the latest version this is what we're seeing.

```
Because explorer >= 0.9.0 depends on rustler ~> 0.34.0 and wasmex >= 0.9.2 depends on rustler ~> 0.35.0, explorer >= 0.9.0 is incompatible with wasmex >= 0.9.2.
And because your app depends on explorer ~> 0.10.0, wasmex >= 0.9.2 is forbidden.
So, because your app depends on wasmex ~> 0.9.2, version solving failed.
** (Mix) Hex dependency resolution failed
```

**Comment by philss** [comment]
@DnOberon oh, I see. Yeah, we need to be more flexible on `:rustler`. For now, you can force override the `:rustler` dependency in your dependency list. So you need to add it to the dependency list (along with explorer) like this:

```elixir
{:rustler, "~> 0.35.0", override: true}
```

It should fix the dependency resolution in your case.

**Comment by DnOberon** [comment]
Awesome that worked for now. Sorry I didn't think of that! Closing this now.
