### ISSUE TITLE
Estimating DataFrame memory use?

### ISSUE THREAD

**Issue by thbar** [elixir-explorer/explorer#1032]
I looked into the code of Explorer & Polars, and wondered if somehow we could expose or estimate the theoretical memory use of a given `DataFrame`, even with a bit of external estimate/computation.

For the context: I am building a "consolidation" of > 1.5k CSV files, a number that will grow steadily in the next few years (containing data for electrical vehicle charging stations of France).

I have decided to use Explorer for that use-case, for the following reasons:
- first to get a higher-level abstraction to manipulate tabular data (compared to list of maps)
- and as a side-effect, for reduced memory consumption (dates/boolean/integer/floats are stored on much fewer bytes, and strings can see considerably reduced memory use via [enums/categories](https://github.com/elixir-explorer/explorer/blob/020fb23e6db145a640b3f1fcb1fe95f404afb8ee/README.md?plain=1#L16), something that will reduce memory use by many MB in my case).

Happy to contribute my findings too, but if someone has pointers on how to estimate theoretical memory use, please let me know!

**Comment by billylanchantin** [comment]
Hi @thbar!

It looks like Polars has an `estimated_size` method available for DataFrames:

* https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.estimated_size.html

That seems like what you need. I think we'd accept a PR to add that functionality.

**Comment by thbar** [comment]
Hi @billylanchantin! Thanks for the pointer; I went ahead and implemented something that appears to work:
- https://github.com/elixir-explorer/explorer/pull/1034

**Comment by thbar** [comment]
Closing, I will try that out on the field. Thanks for the quick review @billylanchantin!

**Comment by halian-vilela** [comment]
Hey @billylanchantin, I'm commenting here because I think a have a much related issue...

Seeking to avoid unnecessary memory allocation, I would like to be able to read some metadata about a given Parquet **before** actually loading it into memory. I've not found any Explorer function that seems to be able to do that...

Do we have something? Actually, what I really need is the number of lines/rows (and I'm pretty sure that it's available as metadata once I have the parquet available).

Thanks!

**Comment by thbar** [comment]
In a similar fashion, a useful optimisation will be (if anyone already knows how to do that) to only keep the columns we have interest for (or even achieve row-filtering before adding it to the in-memory frame). I am not sure if the "lazy" mode allows that or not.

**Comment by billylanchantin** [comment]
@halian-vilela I don't think either Explorer or Polars has a function like that. You may need to use different means to get the info you're looking for.

What's the actual use case? We may be able to avoid your issue all together by lazy loading.

@thbar There is a `columns` option on `DF.from_parquet`. You can mix and match it with the `lazy` option.
```

**Comment by halian-vilela** [comment]
Hi @billylanchantin sorry for the late reply.

My use case would be to avoid, at all costs, reading the whole file just to count the number of lines...

I had this fixed idea that MAYBE it would be possible to read some metadata **without** needing to read the actual data chunks of the file. But I've done a deep dive at the Parquet File Spec and found out that its not that trivial to do in Elixir alone because of how the metadata is serialized using Thift's `TCompactProtocol`.

The problem with the lazyframe approach is that, no matter what, I'll still have to **collapse** it to count using `n_rows` or `query("select count()")`.

But I'm doing some stress tests and until now, if I select just **one** column to count, the memory overhead is drastically improved, so I guess I'll follow this strategy for now.

Thanks

**Comment by billylanchantin** [comment]
@halian-vilela I found this discussion. It's for Python but the ideas should carry over: https://stackoverflow.com/questions/75523498/python-polars-how-to-get-the-row-count-of-a-lazyframe

The accepted solution recommended an approach similar to what I was thinking of. However there is this comment at the bottom:

> does anyone know if `lzdf.select(pl.len()).collect().item()` takes a lot of RAM to compute (or whether its RAM consumption grows proportionally to the dataset size)? I have a script that performs this call before loading the actual data (~0.5M rows), and it fails with OOM error on a k8s pod with 8G of RAM :/

It looks like for this use case, even lazy loading may require building the whole thing in memory first. That's unfortunate.

Just in case though I'd still try this:

```elixir
require Explorer.DataFrame, as: DF

# Option 1 - port of StackOverflow approach
DF.from_parquet!("file.parquet", lazy: true, columns: [:known_column])
|> DF.summarise(n_rows: size(known_column))
|> DF.collect()

# Option 2 - potential workaround if option 1 doesn't work
DF.from_parquet!("file.parquet", lazy: true, columns: [:known_column])
|> DF.summarise(n_rows: 1 + max(row_index(known_column)))
|> DF.collect()
```

Hopefully that comment is mistaken and this only uses a constant amount of memory.

Also: be wary of lazy-loading in the REPL:

```elixir
iex(1)> require Explorer.DataFrame, as: DF
Explorer.DataFrame
iex(2)> DF.new(a: Enum.to_list(0..1_000_000)) |> DF.to_parquet("example.parquet")
:ok
iex(3)> lazy_df = DF.from_parquet!("example.parquet", lazy: true, columns: [:a])
#Explorer.DataFrame<
  LazyPolars[??? x 1]
  a s64 [0, 1, 2, 3, 4, ...]
>
iex(4)> lazy_df |> DF.summarise(n_rows: size(a))
#Explorer.DataFrame<
  LazyPolars[??? x 1]
  n_rows u32 [50]
>
iex(5)> lazy_df |> DF.summarise(n_rows: size(a)) |> DF.collect
#Explorer.DataFrame<
  Polars[1 x 1]
  n_rows u32 [1000001]
>
```

Notice how `lazy_df |> DF.summarise(n_rows: size(a))` appears to calculate an actual value: `50`. This is just a quirk of how we display lazy frames. (I'm pretty sure it's just showing the result on the first chunk.) I say this just in case you're profiling using `iex`.

**Comment by halian-vilela** [comment]
Hey @billylanchantin thanks for your research and suggestions.

Indeed, I had already achieved a similar result with:

```
DF.from_parquet!("file.parquet", lazy: true)
|> DF.query("select count(known_column) from df")
|> DF.collect()
```

It seems to be memory efficient enough, so I'll stick with it for now and eventually try the other approaches if something goes wrong.
