### ISSUE TITLE
Mismatch dtypes of `Explorer.Series.pow/2` result in data frame and series when mutate with lazy series

### ISSUE THREAD

**Issue by nallwhy** [elixir-explorer/explorer#374]
```elixir
df = Explorer.DataFrame.new(%{a: [1, 2, 3]})

df =
  df
  |> Explorer.DataFrame.mutate_with(fn ldf ->
    %{
      b: Explorer.Series.pow(ldf[:a], ldf[:a]),
      c: Explorer.Series.divide(ldf[:a], ldf[:a])
    }
  end)

# dtype of "b" should be float
%{"b" => :integer, "c" => :float} = df |> Explorer.DataFrame.dtypes()

:float = df[:b] |> Explorer.Series.dtype()
:float = df[:c] |> Explorer.Series.dtype()
```

**Comment by nallwhy** [comment]
It will happen after pow/2 between series is allowed.

**Comment by philss** [comment]
@nallwhy I choose to keep it as float because it's common to have `pow/2` operations with integers that the result is a float. Please take a look: https://github.com/pola-rs/polars/issues/4796

I think we should standardize the eager implementation to always return float as well. WDYT?

cc/ @josevalim @cigrainger

**Comment by josevalim** [comment]
Nx allows power of integers and the result is an integer. If a negative number is given as exponent, it raises.

**Comment by nallwhy** [comment]
Is it possible to don't follow the result of polars?

**Comment by philss** [comment]
> Is it possible to don't follow the result of polars?

I think only with casting. We would need to cast the resultant series.

**Comment by josevalim** [comment]
Maybe `pow` in Polars has the same semantics as Python, which is that it returns integer for integers and float for floats. If that's the case, I would rather align Explorer to expect the same result as Polars/Python. Which is also how Nx and Elixir behaves.

**Comment by josevalim** [comment]
I would even go ahead and suggest to rename to `power` to match `Nx`.

**Comment by billylanchantin** [comment]
Yesterday I mentioned that passing an `out_dtype` to the backend may be the way to address this issue. After digging more into it I think I was mistaken.

After @philss's original issue the Polars team has since raised a follow-up issue:

  * https://github.com/pola-rs/polars/issues/9051

It seems they weren't satisfied with the unnecessary cast to float either. In that issue they describe the [plan](https://github.com/pola-rs/polars/issues/9051#issuecomment-1672841511) (paraphrased):

```
pow(uint,  uint)  = uint
pow(int,   uint)  = int
pow(int,   int)   = float
pow(float, int)   = float
pow(int,   float) = float
pow(float, float) = float
```

Essentially, Polars can in theory determine the `out_dtype` from the `in_dtype`s alone because they have access to `uint`. There is a (currently open) PR to make this change:

  * https://github.com/pola-rs/polars/pull/10446

We don't have an unsigned integer on the Elixir side, so we can't do the same thing.

I see three options:

  1. Add a dtype equivalent to `uint` so we can follow Polars' lead.
  2. Cast the result to `:integer` if both the `left` and `right` series were non-negative.
  3. Live with the inconsistency.

Option 1 seems fairly involved, though not impossible. Also we'd need to wait until their PR is merged.

Option 2 is computationally costly. We'd need to cast if all values of the series were $\geq 0$. But without a discerning dtype, the only way to know if we needed to cast would be to check all the values:

```elixir
all_non_neg? = fn s -> Explorer.Series.all_equal(s, Explorer.Series.abs(s)) end

if all_non_neg?.(left) and all_non_neg?.(right) do
  cast(s, :integer)
else
  s
end
```

But if we're OK with the cost, then I _think_ adding this check then passing the `out_dtype` to the backend is workable.

That said, I lean toward option 3 in the short term. Polars is actively changing their behavior, so we don't even have the option to take advantage of `uint`s. We can revisit once their PR makes its way into a release.

WDYT? /cc @philss @josevalim

**Comment by josevalim** [comment]
We actually want to add unsigned integers and precision numbers, because I am sure we will need to handle some parquet sources, but we have been postponing it for now.

Is it an option to copy Nx?

> If both tensors are integers and the exponent is negative, it will raise, but it may trigger undefined behaviour on some compilers.

So basically, if you want to have negative exponent, you need to cast it to float.

**Comment by billylanchantin** [comment]
> We actually want to add unsigned integers and precision numbers

That would be the correct approach to this problem IMO. Then you can do exactly what polars is planning to do.

> Is it an option to copy Nx?

I think you run into the same issue. Raising vs. post-casting are both good approaches. But it's O(n) to check whether or not to do so, right?

**Comment by josevalim** [comment]
So I guess the best option for now is to say it always returns a float and we will eventually align when we add unsigned integers?

**Comment by billylanchantin** [comment]
Yes I think so.

**Comment by billylanchantin** [comment]
Rust Polars 0.36.2 was just released which includes the enhancement discussed above.

* Rust Polars 0.36.2: https://github.com/pola-rs/polars/releases/tag/rs-0.36.2
* Enhancement: https://github.com/pola-rs/polars/pull/10446

Now that we have uint support, after we upgrade to 0.36.2 it should be straightforward to fix this issue.

**Comment by billylanchantin** [comment]
The example now results in the correct types! 🎉 

```elixir
df1 = Explorer.DataFrame.new(%{a: [1, 2, 3]})
# #Explorer.DataFrame<
#   Polars[3 x 1]
#   a s64 [1, 2, 3]
# >

df2 = Explorer.DataFrame.mutate_with(df1, fn ldf ->
  %{
    b: Explorer.Series.pow(ldf[:a], ldf[:a]),
    c: Explorer.Series.divide(ldf[:a], ldf[:a])
  }
end)
# #Explorer.DataFrame<
#   Polars[3 x 3]
#   a s64 [1, 2, 3]
#   b f64 [1.0, 4.0, 27.0]
#   c f64 [1.0, 1.0, 1.0]
# >

df2.dtypes
# %{"a" => {:s, 64}, "b" => {:f, 64}, "c" => {:f, 64}}
```

And the expression-based version for good measure:

```elixir
df2 = Explorer.DataFrame.mutate(df1, b: a ** a, c: a / a)
# #Explorer.DataFrame<
#   Polars[3 x 3]
#   a s64 [1, 2, 3]
#   b f64 [1.0, 4.0, 27.0]
#   c f64 [1.0, 1.0, 1.0]
# >

df2.dtypes                                              
# %{"a" => {:s, 64}, "b" => {:f, 64}, "c" => {:f, 64}}
```
