### ISSUE TITLE
Normalize numeric columns after perform a LazyFrame IO read

### ISSUE THREAD

**Issue by philss** [elixir-explorer/explorer#471]
We want to keep numeric columns only using either `Int64` of `Float64`, so we should cast integer and float columns that are not using those two types.

Extracted from https://github.com/elixir-nx/explorer/pull/470

**Comment by cigrainger** [comment]
@philss do we do this? Happy to pick it up if not.

**Comment by josevalim** [comment]
I don't think we do it, so a patch is necessary. But at some point we should also discuss adding more precision to types (which I know you don't want to :D).

**Comment by cigrainger** [comment]
I have seen the light and am happy with adding more precision to types, especially since we get zero copy with Nx. I think it's possible we should have a default precision so we can still have just `:integer` and `:float` (or some other solution to keep things simple for easy data exploration) but I could be convinced otherwise. I do think folks will footgun if we're not careful.

**Comment by josevalim** [comment]
I think keeping :integer and :float, with their current meanings, is completely fine, as they are the closest to their current precision on the Erlang VM.

**Comment by cigrainger** [comment]
So we would just add more types w/ additional precision? E.g. keep `:integer` but add `:i32` for example?

**Comment by josevalim** [comment]
I would follow Nx here. So I would add: {:u, 32}, {:s, 32}, {:f, 32} and so on. Probably start with floats as they are simpler.

**Comment by philss** [comment]
I'm closing this issue because it does not makes sense anymore. I should open a new issue for the remaining work on supporting the new integer dtypes.
