### ISSUE TITLE
Use sink cloud versions of ipc

### ISSUE THREAD

**Issue by josevalim** [elixir-explorer/explorer#705]
We need a new Explorer version:

* https://github.com/pola-rs/polars/pull/10060
* https://github.com/pola-rs/polars/pull/11008

**Comment by Qqwy** [comment]
@josevalim FYI I briefly spoke with Ritchie on the Polars Discord today and he merged the `sink_ipc_cloud` PR just now, so work on the Explorer side can now continue!

**Comment by philss** [comment]
First of all: awesome work there on Polars, @Qqwy !! :tada: 

Just to let you know that I'm working on this to bring the functionality to Explorer :)

**Comment by philss** [comment]
Hey @Qqwy, I had some issues trying to make the Sink IPC work, so I opened an issue upstream: https://github.com/pola-rs/polars/issues/13614

I tried to find a fix for it, but I couldn't understand where the "block_on" is happening (twice). Would you mind to take a look?

**Comment by Qqwy** [comment]
Hi there! Thanks for tagging me, I'll dig into this problem. `block_on` is probably called from within the `#[tokio::main]` decorators. The crash happens because for some reason an attempt is made to start an async Tokio runtime from within a pre-existing Tokio runtime. _Why_ that happens is of course the thing to figure out as it shouldn't.

Just to double-check: Is this only a problem with sink_ipc_cloud and not with sink_parquet_cloud?

**Comment by josevalim** [comment]
As far as _I_ know, only ipc. @philss will be able to confirm though!

**Comment by philss** [comment]
@Qqwy yeah, it's only with the `sink_ipc_cloud`. The `sink_parquet_cloud` is working good, and it's already in main.

PS: sorry, I didn't see the ping before :grimacing:

**Comment by Qqwy** [comment]
@philss I have created a PR with a fix on the Polars repo: https://github.com/pola-rs/polars/pull/14262
