### ISSUE TITLE
DateTime with timezone could not be normalised

### ISSUE THREAD

**Issue by halian-vilela** [elixir-explorer/explorer#744]
Hey guys!

Using:  `{:explorer, "~> 0.7.1"}`

I was trying to read a Parquet in Livebook. One of my columns has timestamp strings in the following format: `2023-11-20 03:00:00` but when trying to parse it, something is sticking some timezone information as metadata.

Hence, I'm receiving the following error:

```elixir
** (FunctionClauseError) no function clause matching in Explorer.PolarsBackend.Shared.normalise_dtype/1    
    
    The following arguments were given to Explorer.PolarsBackend.Shared.normalise_dtype/1:
    
        # 1
        "datetime[ns, UTC]"
    
    Attempted function clauses (showing 10 out of 15):
    
        def normalise_dtype("binary")
        def normalise_dtype("bool")
        def normalise_dtype("cat")
        def normalise_dtype("date")
        def normalise_dtype("time")
        def normalise_dtype("datetime[ms]")
        def normalise_dtype("datetime[ns]")
        def normalise_dtype("datetime[μs]")
        def normalise_dtype("duration[ms]")
        def normalise_dtype("duration[ns]")
        ...
        (5 clauses not shown)
    
    (explorer 0.7.1) lib/explorer/polars_backend/shared.ex:157: Explorer.PolarsBackend.Shared.normalise_dtype/1
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (explorer 0.7.1) lib/explorer/polars_backend/shared.ex:80: Explorer.PolarsBackend.Shared.create_dataframe/1
    (explorer 0.7.1) lib/explorer/polars_backend/lazy_frame.ex:176: Explorer.PolarsBackend.LazyFrame.from_parquet/3
    (explorer 0.7.1) lib/explorer/data_frame.ex:755: Explorer.DataFrame.from_parquet!/2
     my_path/explorer_explorations.livemd#cell:v2ue37r2nqfw7bu4fxuufm3wbfoafrxl:3: (file)
```
    
Other columns are simple strings, ints and floats, so only the timestamp one seems to be the source of the problem.
    
    
Thanks

**Comment by billylanchantin** [comment]
Hi @halian-vilela :)

Explorer currently only supports naive datetimes. Can you show the code that produces the error?

**Comment by billylanchantin** [comment]
That does seem quite by the book.

So I'm not as familiar with parquet files as I'd like to be. I'll weigh in, but I think @philss or @cigrainger will know more.

My initial reading of this issue is that, unfortunately, your parquet file simply has a type that we don't support. The fix would be to alter the file so that column is of a type we do support.

One thing to note is that you can supply a list of columns with the `columns` option. If there is some exploration you could do that doesn't require the timestamp column, you could probably do `columns: all_columns_except_timestamp` while you wait for the others to weigh in.

**Comment by philss** [comment]
> My initial reading of this issue is that, unfortunately, your parquet file simply has a type that we don't support. The fix would be to alter the file so that column is of a type we do support.

I think this is correct! We just don't support datetimes that contains the timezone yet.
An alternative for the [`:columns` option](https://hexdocs.pm/explorer/Explorer.DataFrame.html#from_parquet/2) is to use [`Explorer.DataFrame.discard/2`](https://hexdocs.pm/explorer/Explorer.DataFrame.html#discard/2) to drop the unwanted column from the DF.
Since the problem only occurs when we want to inspect the DF, this should work fine.

**Comment by josevalim** [comment]
It is not very complex, we are adding new data types all the time, we just need to get around to adding this one. :) Although we would need a timezone database to convert some of those back to Elixir. But we should at least be able to read them from Polars side.

**Comment by philss** [comment]
> That's because we don't even have a chance to get to the resulting data-frame after the attempted conversion.

@halian-vilela I thought we could do without passing by the inspection of the resultant DF :/

Did you try something like this (without an intermediate assignment)?

```elixir
df =
  Kino.FS.file_spec("2023-11-21_file.parquet")
  |> Explorer.DataFrame.from_parquet!(lazy: true)
  |> Explorer.DataFrame.discard("your-column")
```

And about adding a new type: we could start by supporting datetimes with the UTC timezone only, and then we add the timezone database to convert back to Elixir.

**Comment by josevalim** [comment]
> And about adding a new type: we could start by supporting datetimes with the UTC timezone only, and then we add the timezone database to convert back to Elixir.

Great idea!

**Comment by josevalim** [comment]
@billylanchantin we can close this one, right?

**Comment by billylanchantin** [comment]
@josevalim I think so! https://github.com/elixir-explorer/explorer/pull/903 should have added support for this.

The real proof would be if @halian-vilela is able to parse the original `.parquet` file using `main`. But I'd also be ok with closing this issue on faith and letting someone reopen if we didn't get it right :)

**Comment by halian-vilela** [comment]
Hi @billylanchantin ! Thanks for reaching out! I'll give it a try later today or tomorrow morning and tell you next!
